### PR TITLE
add type declarations

### PR DESCRIPTION
**Pull request by mcshaz**
since the project is in Typescript, it should be easy to export a .d.ts file as well - this will make it much easier for others using your library with typescript.

### CODE REVIEW

**Comment by mcshaz** [comment]
it is failing on Travis and my machine (above), but it would not build for me before I made the changes.

**Comment by dumbmatter** [comment]
I imagine this would only cover the main entry point, which is not optimal because a lot of other people import things like FDBKeyRange.

Also, an alternative idea would be to simply declare these variables to have the same type as the native IndexedDB ones. I haven't tried that, but the API is identical, so it should work I guess... might be easier than fighting TypeScript to get it to output things correctly.

**Comment by mcshaz** [comment]
actually ignore - looking at the code it is just polyfilling the window (/global/self) object and doesnt actually export anything

**Comment by ksnyde** [comment]
What happened to this thread? I am eager to use this in conjunction with my **Dexie** testing but simply adding:

```typescript
import 'fake-indexeddb/auto';
```

is not getting **Dexie** to pick up the API:

> indexedDB API not found. If using IE10+, make sure to run your code on a server URL (not locally). If using old Safari versions, make sure to include indexedDB polyfill.

Usually when this happens I then try to dig into things with the help of TypeScript. Sadly it would appear that we didn't quite get to the finish line in exporting the symbols.

**Comment by dumbmatter** [comment]
TypeScript types don't have any affect at runtime, so it's probably unrelated to your error.

**Comment by ksnyde** [comment]
That is true of course but I find typed interface a very efficient way of exploring a new API or library :)

**Pull request closed without merging**
